name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend image
        run: docker build -t grammair-backend ./backend
      - name: Build frontend image
        run: docker build -t grammair-frontend ./frontend
      - name: Run backend container
        run: docker run -d -p 8000:8000 --name backend grammair-backend
      - name: Run frontend container
        run: docker run -d -p 5173:5173 --name frontend --link backend grammair-frontend
      - name: Test backend health
        run: |
          sleep 5
          curl --fail http://localhost:8000/ || exit 1
      - name: Test frontend health
        run: |
          sleep 5
          curl --fail http://localhost:5173/ || exit 1
